version: 2
jobs:
  build:
    branches:
      only:
        - development
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install -e ~/repo
      - run:
          name: run tests
          command: |
            python -m unittest ~/repo

